### ISSUE TITLE
issue with postgresql 10

### ISSUE THREAD

**Issue by johnfelipe** [mysociety/sayit.mysociety.org#105]
Downloading psycopg2-2.5.5.tar.gz (779kB)
		100% |████████████████████████████████| 788kB 1.5MB/s
		Complete output from command python setup.py egg_info:
		running egg_info
		creating pip-egg-info/psycopg2.egg-info
		writing pip-egg-info/psycopg2.egg-info/PKG-INFO
		writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
		writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
		writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
		Error: could not determine PostgreSQL version from '10.0'

		----------------------------------------
	Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xDJVzS/psycopg2/

how solved?

**Comment by dracos** [comment]
SayIt has upgraded its version of psycopg2 to cope with postgresql 10.
