### ISSUE TITLE
about image for avatar

### ISSUE THREAD

**Issue by johnfelipe** [mysociety/sayit.mysociety.org#57]
domain/speech/395:

![issue](https://cloud.githubusercontent.com/assets/428820/4114469/23de61c0-3269-11e4-9095-b0fd38e177dc.png)

if you look name is above profile image

**Comment by johnfelipe** [comment]
http://concejodemedellin.felipeurrego.com/speech/771, circular thumbnail is overlap, how fix that?

**Comment by dracos** [comment]
You have changed the template to not use a square image, so there is nothing we can do to help you. Change it back.

**Comment by johnfelipe** [comment]
Hi, me again
http://concejodemedellin.felipeurrego.com/speech/860
Then i dont know why this behavior, can you please enter in my production instance?
