### ISSUE TITLE
error upload URL of a head shot

### ISSUE THREAD

**Issue by johnfelipe** [mysociety/sayit.mysociety.org#89]
I update speaker and not work image profile:

![speaker2](https://cloud.githubusercontent.com/assets/428820/5530891/7817f832-89f3-11e4-8f26-a47da70a0007.png)
![speaker](https://cloud.githubusercontent.com/assets/428820/5530890/7814f312-89f3-11e4-93d8-d959b00dc73e.png)

All update and load with akoma ntoso: https://github.com/johnfelipe/akomantosomedellin/tree/199-a-210

**Comment by fernandouval** [comment]
Hey! What is not working is speaker.image_cache, for example in  {% if speaker.image_cache %}{{ speaker.image_cache|thumbnail_url:'speaker-thumb' }} on line 30 of /virtualenv-sayit/src/django-sayit/speeches/templates/speeches/speaker_list.html

If you just leave "<img src="{% if speaker.image %}{{ speaker.image }}{% else %}{% static "speeches/i/a.png" %}{% endif %}", it works.

May be it has to do with the location of the uploads folder?

**Comment by johnfelipe** [comment]
Hello please tell me something about say  @fernandouval

**Comment by johnfelipe** [comment]
http://concejodemedellin.felipeurrego.com/speaker/%C3%A1lvaro-m%C3%BAnera-builes, have image, but
http://concejodemedellin.felipeurrego.com/acta-200#s56, dont and
http://concejodemedellin.felipeurrego.com/speech/56, dont have to

Please help

**Comment by dracos** [comment]
@johnfelipe As ever, I am afraid that  you do not provide enough information and so we are unable to help you. I see an `<img src="">` in the source code of the speech page, so I know that you have edited the templates, but I do not know what you have done. From the header of `/speech/56`, I can see that it tries to use an image located at http://concejodemedellin.felipeurrego.com/media/speakers/concejodemedellin/19607.jpg but that is not present. So something in your setup is not correct for serving uploaded files, or uploading the files, as has already been suggested, or it is something else – you will have to investigate. Is the issue saving files to the uploads folder, or serving files from the uploads folder? When you set the "image" field to a URL when editing a speaker and save, is the image downloaded from that URL and saved to your uploads folder? Are there images present in your uploads folder? Take each step of the process, see if you can work out if that step is working, and track down at what point something is not working.

There is no bug in the image uploading and serving as far as I am aware, it is working fine on other installations.

**Comment by dracos** [comment]
I would guess that you have not set up your web server to serve the uploaded files (contained in the uploads folder) at `/media/`.

**Comment by johnfelipe** [comment]
where is that folder?, i need set up in nginx?

**Comment by dracos** [comment]
Where that folder is is down to how you have set up your server, but I imagine it will be an `uploads` folder in the same place as the `sayit.mysociety.org` folder (perhaps in `/home/sayit`?). Yes, you need to set up your web server to serve static and media files in production. I assume you already have a section that is something like:
```
    location /static/ {
        alias /home/sayit/collected_static/;
    }
```
So you need to add one like:
```
    location /media/ {
        alias /home/sayit/uploads/;
    }
```

**Comment by johnfelipe** [comment]
This is my /etc/nginx/sites-available/sayit:

	upstream app_server {
		server localhost:8000;
	}

	server {
		listen 80 default_server;
		listen [::]:80 default_server ipv6only=on;

		root /home/sayit/sayit.mysociety.org/web;
		server_name localhost felipeurrego.com;

		location /static/ {
			alias /home/sayit/collected_static/;
		}
		
		location /media/ {
			alias /home/sayit/uploads/;
		}
		
		location / {
			try_files $uri @proxy_to_app;
		}

		location @proxy_to_app {
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header Host $http_host;
			proxy_redirect off;
			proxy_pass http://app_server;
		}
	}

restart all and still dont work

**Comment by dracos** [comment]
http://concejodemedellin.felipeurrego.com/media/speakers/concejodemedellin/19607.jpg now works whereas before it gave a 404, so something now works that did not before.

As for why things still don't work, am I correct in what I already said that you have changed `speech_detail.html`, and possibly other templates? Perhaps you should change them back. If you look at the source of http://concejodemedellin.felipeurrego.com/speech/56 you will see the `og:image` in the header is correct and giving the right URL whilst the one lower down is not, and yet in the SayIt code they are produced the same way, therefore I think you have changed things in the code.

**Comment by johnfelipe** [comment]
Work:

http://concejodemedellin.felipeurrego.com/speaker/carlos-alberto-bayer-cano
http://concejodemedellin.felipeurrego.com/acta-200#s54
http://concejodemedellin.felipeurrego.com/speech/54

Dont work:

http://concejodemedellin.felipeurrego.com/speaker/bernardo-alejandro-guerra-hoyos
http://concejodemedellin.felipeurrego.com/acta-199#s37
http://concejodemedellin.felipeurrego.com/speech/37

Why this behavior?

**Comment by dracos** [comment]
I don't know. As it's working for the first one, and others, clearly the code is working okay, and issues you are having are down to things you must have done. Have you tried setting the image URL again and re-saving? The file itself is there http://concejodemedellin.felipeurrego.com/media/speakers/concejodemedellin/19591.jpg – have you checked whether the thumbnail files are generated? I am not going to repeat the questions I already suggested to you <a href="https://github.com/mysociety/sayit.mysociety.org/issues/89#issuecomment-74551750">above</a>, they are all still just as relevant.

**Comment by johnfelipe** [comment]
i dont know whats going on but i have edit:

speech_detail
speech
speaker_detail
speaker_list

this

```<img src="{% if speaker.image_cache %}{{ speaker.image_cache|thumbnail_url:'speaker-thumb' }}{% elif speaker.image %}{{ speaker.image }}{% else %}{% static "speeches/i/a.png" %}{% endif %}"```

to this

```<img src="{% if speaker.image_cache %}{{ MEDIA_URL }}{{speaker.image_cache }}{% elif speaker.image %}{{ speaker.image }}{% else %}{% static "speeches/i/a.png" %}{% endif %}"```

And this work fine, look:

http://concejodemedellin.felipeurrego.com/speakers

All upload in /home/sayit/collected_static/uploads/speakers/concejodemedellin

Please tell me how fix that, is personalized edit

**Comment by dracos** [comment]
All you have done there is remove the code to display a thumbnail image and replace it with code to display the uploaded file directly. That will do what you say, but will therefore mean you don't have shrunken or square thumbnail images, as you then complain about elsewhere. The issue is not with the templates, they are correct. If the issue is the thumbnail images aren't being generated (but are sometimes), then you need to investigate why, for which I have already given you various ideas above. We use easy-thumbnails for thumbnail generation, you could try generating thumbnails manually at the command line and seeing if the process works okay, or if not, why not.

**Comment by johnfelipe** [comment]
i edit

collected_static/css/project.css

.speech-single-speech .speech__meta-data: margin-top: 1.2em;

And works for me

http://concejodemedellin.felipeurrego.com/speech/1808
