### ISSUE TITLE
Issue in translate

### ISSUE THREAD

**Issue by johnfelipe** [mysociety/sayit.mysociety.org#92]
When:

    ./manage.py compilemessages

Show me this:

	CommandError: Execution of msgfmt failed: /home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:42: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:39: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:425: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:353: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:429: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:357: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:434: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:364: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:440: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:370: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:444: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:374: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:448: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:378: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:453: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:398: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:473: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:416: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:479: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:422: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:692: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:594: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:700: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:525: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:706: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:529: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:710: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:533: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:714: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:537: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:718: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:541: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:723: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:546: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:727: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:550: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:731: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:554: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:735: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:558: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:739: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:562: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:743: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:566: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:747: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:570: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:751: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:574: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:755: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:578: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:759: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:582: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:763: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:586: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:767: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:590: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:771: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:600: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:777: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:606: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:781: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:610: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:785: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:614: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:789: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:618: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:793: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:622: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:797: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:626: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:801: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:630: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:805: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:634: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:809: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:638: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:813: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:642: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:817: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:646: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:821: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:650: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:825: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:654: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:829: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:658: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:834: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:673: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:849: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:687: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:1090: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:1077: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:1094: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:1083: ...this is the location of the first definition
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:1100: duplicate message definition...
	/home/felipe/sayit/sayit.mysociety.org/sayit_mysociety_org/locale/zh_TW/LC_MESSAGES/django.po:1087: ...this is the location of the first definition
	msgfmt: found 48 fatal errors

**Comment by dracos** [comment]
Fixed in 627c558288573345ccf8c6f7cffe35ba04556f0d sorry about that.
