### ISSUE TITLE
Implement standard mySociety footer on sayit.mysociety.org and the default SayIt instance theme

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/sayit.mysociety.org#96]
Moving across from mysociety/sysadmin#676 which discusses more prominent branding across all of our sites as a way of making their provenance clear.

**Comment by zarino** [comment]
Once this ticket is done, make sure to update the list on https://github.com/mysociety/standard-footer/issues/9#issuecomment-228766046 and notify Matthew so he can deploy.

**Comment by dracos** [comment]
Not yet done.

**Comment by dracos** [comment]
Really done.
